version: "3"

services: 
  api: 
    build: ../server
    ports: 
      - "8000:8000"
    volumes:
      - ../server:/usr/app/server
    command: yarn dev

  frontend:
    build: ../frontend
    image: frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/usr/app/frontend
    command: yarn dev
